context:
  version: "0.2.1"

package:
  name: libasdf
  version: ${{ version }}

source:
  url: https://github.com/asdf-format/libasdf/releases/download/${{ version }}/libasdf-${{ version }}.tar.gz
  sha256: a1d20b8a8baf10590a6404ace04c35bf23b1517d143a7a88433e2e1e5b9d536b

build:
  number: 0
  skip: win
  script:
    - ./configure --prefix="${PREFIX}" --disable-docs
    - make -j${CPU_COUNT}
    - |
      if [[ "${CONDA_BUILD_CROSS_COMPILATION:-}" != "1" || "${CROSSCOMPILING_EMULATOR:-}" != "" ]]; then
          make check || (cat tests/test-suite.log && exit 1)
      fi
    - make install

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
    - pkg-config
  host:
    - bzip2
    - libfyaml
    - libmd
    - lz4-c
    - zlib
    - libstatgrab
    - if: osx
      then: argp-standalone
  run_exports:
    - ${{ pin_subpackage('libasdf', upper_bound='x.x') }}

tests:
  - package_contents:
      bin:
        - asdf
      lib:
        - asdf
      include:
        - asdf.h
        - asdf/config.h
        - asdf/version.h
  - script: asdf --help

about:
  homepage: https://github.com/asdf-format/libasdf
  summary: "C implementation of ASDF"
  description: |
    libasdf is largely a wrapper around libfyaml but with an understanding of
    the structure of ASDF files, with the capability to read and write binary
    block data, as well as typed getters for metadata in the ASDF tree.
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - third_party/STC/LICENSE
  documentation: https://libasdf.readthedocs.io/
  repository: https://github.com/asdf-format/libasdf/

extra:
  recipe-maintainers:
    - embray
    - jhunkeler
